# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f98a8cd2f77887f05f242d41d14371abb9916c51e4612b96fd3588478e2cdb173337c447f7af9596748ec4f88427034acda74b7b0d289fa3d27f9ce6ac224131

test:
  secret_key_base: 1aab64f625e4c077b7b10cfc7a2fd5bb77e0d6e839c5ac9ad0bf8a7205e8da76ad31d3c8f94f2d3b27c9a632a35a552b735d3a8fb19339822753095e2ea3468f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>

global: &global_defaults
  env:
    current_ruby: 2.2.1
    rvm_gemset: seberov
    rvm_ruby_string: 2.2.1@severov
