phones:
  default: &default_phone +420 603 933 909
  default_long: *default_phone
  default_short: '603 933 909'
  default_short_dashed: '603-933-909'
google_api:
  maps_key: 'AIzaSyCNLWjn5799hEu-qIfL5nHU1lskw3Wnxqs'
