emails:
  default: 'prodej@statekseberov.cz'
  default_from: 'ownroad.show@gmail.com'
  default_to: 'prague.reactor@gmail.com' # !DESTROY_AFTER
  callback_to: 'prague.reactor@gmail.com' # !DESTROY_AFTER
